### ISSUE TITLE
Personal Info in repository

### ISSUE THREAD

**Issue by rybodiddly** [hitman3r44/kijiji-reposter-sumit#1]
Just a heads up, you've uploaded your user folder to the repository. If you look at my original code [here](https://github.com/rybodiddly/Kijiji-Reposter), you'll notice it does a check for the user folder. If it does not exist, it will create it. So you might want to delete that folder, as it contains your user number, email and area code in the ad files, or at least add it to your gitignore. You can close this, as its not really an issue, more just a pointer.

**Comment by hitman3r44** [comment]
Thankx, I clone this repository do some kind of development, suer I will put that information into the .gitignore file.
